apiVersion: v1
kind: Service
metadata:
  name: pdfgenerator-dotnet-service
spec:
  selector:
    app: pdfgenerator-dotnet
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
